import { Product, Review, Testimonial, FAQ } from '@/types';

// Mock product data
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Premium Garden Soil Mix',
    slug: 'premium-garden-soil-mix',
    description: 'Our premium garden soil mix is specially formulated to provide optimal growing conditions for vegetables, flowers, and herbs. Rich in organic matter and essential nutrients, this soil promotes healthy root development and vigorous plant growth.',
    shortDescription: 'Perfect blend for vegetable and flower gardens',
    price: 899,
    originalPrice: 1199,
    images: [
      'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800',
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    ],
    category: 'garden-lawn',
    stock: 150,
    rating: 4.8,
    reviewCount: 247,
    benefits: [
      'Improves soil aeration and drainage',
      'Rich in organic matter (40% compost)',
      'pH balanced (6.0-7.0)',
      'Contains beneficial microorganisms',
      'Promotes strong root development',
    ],
    specifications: [
      { label: 'Weight', value: '25 kg' },
      { label: 'Coverage', value: 'Up to 200 sq ft' },
      { label: 'pH Level', value: '6.0 - 7.0' },
      { label: 'Organic Content', value: '40%' },
      { label: 'Composition', value: 'Compost, Peat, Perlite, Vermiculite' },
    ],
    tags: ['organic', 'garden', 'vegetables', 'flowers'],
    certifications: ['Organic Certified', 'Quality Tested'],
    featured: true,
    popular: true,
  },
  {
    id: '2',
    name: 'Indoor Plant Potting Mix',
    slug: 'indoor-plant-potting-mix',
    description: 'Specially designed for indoor plants, this lightweight potting mix ensures excellent drainage while retaining optimal moisture levels. Perfect for houseplants, succulents, and tropical plants.',
    shortDescription: 'Ideal for all indoor houseplants',
    price: 599,
    images: [
      'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=800',
    ],
    category: 'indoor-planting',
    stock: 200,
    rating: 4.7,
    reviewCount: 189,
    benefits: [
      'Excellent drainage properties',
      'Lightweight formula',
      'Prevents root rot',
      'Suitable for all indoor plants',
      'Added nutrients for 3 months',
    ],
    specifications: [
      { label: 'Weight', value: '10 kg' },
      { label: 'pH Level', value: '5.5 - 6.5' },
      { label: 'Moisture Retention', value: 'Medium' },
      { label: 'Drainage', value: 'Excellent' },
    ],
    tags: ['indoor', 'houseplants', 'lightweight'],
    featured: true,
    popular: true,
  },
  {
    id: '3',
    name: 'Industrial Remediation Soil',
    slug: 'industrial-remediation-soil',
    description: 'Professional-grade soil solution for industrial site remediation. Specially treated to neutralize contaminants and restore soil health for commercial and industrial applications.',
    shortDescription: 'Professional grade for site remediation',
    price: 15999,
    images: [
      'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800',
    ],
    category: 'industrial-remediation',
    stock: 50,
    rating: 4.9,
    reviewCount: 67,
    benefits: [
      'Neutralizes soil contaminants',
      'Certified for industrial use',
      'Promotes soil recovery',
      'Meets environmental standards',
      'Bulk discounts available',
    ],
    specifications: [
      { label: 'Weight', value: '1000 kg (bulk)' },
      { label: 'pH Level', value: 'Adjustable' },
      { label: 'Treatment', value: 'Chemical neutralization' },
      { label: 'Certification', value: 'EPA approved' },
    ],
    tags: ['industrial', 'remediation', 'professional'],
    certifications: ['EPA Approved', 'Industrial Grade'],
    featured: false,
    popular: false,
  },
  {
    id: '4',
    name: 'Organic Lawn Fertilizer Soil',
    slug: 'organic-lawn-fertilizer-soil',
    description: 'Transform your lawn with our nutrient-rich organic soil blend. Designed to promote lush, green grass growth while improving soil structure and water retention.',
    shortDescription: 'For vibrant, healthy lawns',
    price: 1299,
    originalPrice: 1599,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    ],
    category: 'garden-lawn',
    stock: 120,
    rating: 4.6,
    reviewCount: 312,
    benefits: [
      'Promotes thick, green grass',
      '100% organic ingredients',
      'Improves water retention',
      'Safe for pets and children',
      'Slow-release nutrients',
    ],
    specifications: [
      { label: 'Weight', value: '20 kg' },
      { label: 'Coverage', value: 'Up to 500 sq ft' },
      { label: 'NPK Ratio', value: '10-5-5' },
      { label: 'Type', value: '100% Organic' },
    ],
    tags: ['organic', 'lawn', 'fertilizer', 'pet-safe'],
    certifications: ['Organic Certified', 'Pet Safe'],
    featured: true,
    popular: true,
  },
  {
    id: '5',
    name: 'Cactus & Succulent Mix',
    slug: 'cactus-succulent-mix',
    description: 'Specially formulated for cacti and succulents, this fast-draining soil mix prevents water-logging and root rot while providing essential nutrients.',
    shortDescription: 'Perfect for cacti and succulents',
    price: 449,
    images: [
      'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=800',
    ],
    category: 'indoor-planting',
    subcategory: 'specialty',
    stock: 180,
    rating: 4.8,
    reviewCount: 156,
    benefits: [
      'Excellent drainage',
      'Prevents root rot',
      'Contains sand and perlite',
      'pH optimized for desert plants',
      'Lightweight formula',
    ],
    specifications: [
      { label: 'Weight', value: '5 kg' },
      { label: 'pH Level', value: '6.0 - 7.5' },
      { label: 'Drainage', value: 'Very Fast' },
      { label: 'Components', value: 'Sand, Perlite, Peat' },
    ],
    tags: ['succulent', 'cactus', 'indoor', 'drainage'],
    featured: false,
    popular: true,
  },
  {
    id: '6',
    name: 'Raised Bed Garden Soil',
    slug: 'raised-bed-garden-soil',
    description: 'Complete soil solution for raised bed gardens. This premium mix combines the perfect balance of drainage, aeration, and nutrient retention for productive vegetable gardening.',
    shortDescription: 'Optimized for raised bed gardening',
    price: 1499,
    images: [
      'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=800',
    ],
    category: 'garden-lawn',
    stock: 95,
    rating: 4.9,
    reviewCount: 203,
    benefits: [
      'Perfect for raised beds',
      'High organic content',
      'Excellent water retention',
      'Rich in nutrients',
      'Weed-free formula',
    ],
    specifications: [
      { label: 'Weight', value: '40 kg' },
      { label: 'Coverage', value: '1 cubic foot' },
      { label: 'pH Level', value: '6.5 - 7.0' },
      { label: 'Organic Content', value: '50%' },
    ],
    tags: ['raised-bed', 'vegetables', 'organic', 'garden'],
    certifications: ['Organic Certified'],
    featured: true,
    popular: true,
  },
];

// Mock reviews
export const mockReviews: Review[] = [
  {
    id: '1',
    productId: '1',
    userName: 'Priya Sharma',
    rating: 5,
    title: 'Best soil I\'ve used!',
    comment: 'My vegetable garden has never looked better. The tomatoes are thriving, and the drainage is perfect. Highly recommend!',
    date: '2024-10-15',
    verified: true,
    helpful: 24,
  },
  {
    id: '2',
    productId: '1',
    userName: 'Rajesh Kumar',
    rating: 4,
    title: 'Great quality soil',
    comment: 'Very good product. My plants are growing well. Only minor issue was delivery took a bit longer than expected.',
    date: '2024-10-10',
    verified: true,
    helpful: 12,
  },
  {
    id: '3',
    productId: '2',
    userName: 'Anjali Mehta',
    rating: 5,
    title: 'Perfect for my houseplants',
    comment: 'My monstera and pothos are loving this mix. No more root rot issues!',
    date: '2024-09-28',
    verified: true,
    helpful: 18,
  },
];

// Mock testimonials
export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Vikram Patel',
    role: 'Home Gardener',
    content: 'Soil Guard has transformed my garden. Their expert advice and quality products have helped me grow the best vegetables I\'ve ever had!',
    rating: 5,
  },
  {
    id: '2',
    name: 'Sneha Reddy',
    role: 'Landscape Designer',
    company: 'GreenScape Designs',
    content: 'As a professional, I trust Soil Guard for all my projects. Their industrial solutions are top-notch and their support team is incredibly helpful.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Arun Desai',
    role: 'Urban Farmer',
    content: 'The chatbot helped me choose the perfect soil for my rooftop garden. Customer service is excellent, and the products deliver results!',
    rating: 5,
  },
];

// Mock FAQs
export const mockFAQs: FAQ[] = [
  {
    question: 'How do I choose the right soil for my needs?',
    answer: 'Use our AI assistant to help you find the perfect soil! Click the chat button and tell us about your project - whether it\'s indoor plants, a garden, or industrial use. Our assistant will recommend the best products based on your specific needs.',
  },
  {
    question: 'What makes Soil Guard products different?',
    answer: 'All our soil products are certified for quality and tested for optimal pH levels, nutrient content, and drainage properties. We use sustainable sourcing and ensure each batch meets strict standards for organic content and environmental safety.',
  },
  {
    question: 'Do you offer bulk discounts?',
    answer: 'Yes! We offer significant discounts for bulk orders, especially for industrial and commercial projects. Contact our sales team or use the chat feature to get a custom quote.',
  },
  {
    question: 'What is your return policy?',
    answer: 'We offer a 30-day satisfaction guarantee. If you\'re not completely satisfied with your purchase, you can return unopened bags for a full refund. Please refer to our Returns & Refunds page for complete details.',
  },
  {
    question: 'How long does delivery take?',
    answer: 'Standard delivery takes 3-5 business days within major cities. For remote areas, delivery may take up to 7 business days. Free shipping is available on orders over ₹2,000.',
  },
];
