import { Product, Review, Testimonial, FAQ } from '@/types';

// Mock product data
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Premium Garden Soil Mix',
    slug: 'premium-garden-soil-mix',
    description: 'Our premium garden soil mix is specially formulated to provide optimal growing conditions for vegetables, flowers, and herbs. Rich in organic matter and essential nutrients, this soil promotes healthy root development and vigorous plant growth.',
    shortDescription: 'Perfect blend for vegetable and flower gardens',
    price: 699,
    originalPrice: 899,
    images: [
      'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800',
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    ],
    category: 'garden-lawn',
    stock: 150,
    rating: 4.8,
    reviewCount: 247,
    benefits: [
      'Improves soil aeration and drainage',
      'Rich in organic matter (40% compost)',
      'pH balanced (6.0-7.0)',
      'Contains beneficial microorganisms',
      'Promotes strong root development',
    ],
    specifications: [
      { label: 'Weight', value: '25 kg' },
      { label: 'Coverage', value: 'Up to 200 sq ft' },
      { label: 'pH Level', value: '6.0 - 7.0' },
      { label: 'Organic Content', value: '40%' },
      { label: 'Composition', value: 'Compost, Peat, Perlite, Vermiculite' },
    ],
    tags: ['organic', 'garden', 'vegetables', 'flowers'],
    certifications: ['Organic Certified', 'Quality Tested'],
    featured: true,
    popular: true,
  },
  {
    id: '2',
    name: 'Indoor Plant Potting Mix',
    slug: 'indoor-plant-potting-mix',
    description: 'Specially designed for indoor plants, this lightweight potting mix ensures excellent drainage while retaining optimal moisture levels. Perfect for houseplants, succulents, and tropical plants.',
    shortDescription: 'Ideal for all indoor houseplants',
    price: 449,
    images: [
      'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=800',
    ],
    category: 'indoor-planting',
    stock: 200,
    rating: 4.7,
    reviewCount: 189,
    benefits: [
      'Excellent drainage properties',
      'Lightweight formula',
      'Prevents root rot',
      'Suitable for all indoor plants',
      'Added nutrients for 3 months',
    ],
    specifications: [
      { label: 'Weight', value: '10 kg' },
      { label: 'pH Level', value: '5.5 - 6.5' },
      { label: 'Moisture Retention', value: 'Medium' },
      { label: 'Drainage', value: 'Excellent' },
    ],
    tags: ['indoor', 'houseplants', 'lightweight'],
    featured: true,
    popular: true,
  },
  {
    id: '3',
    name: 'Industrial Remediation Soil',
    slug: 'industrial-remediation-soil',
    description: 'Professional-grade soil solution for industrial site remediation. Specially treated to neutralize contaminants and restore soil health for commercial and industrial applications.',
    shortDescription: 'Professional grade for site remediation',
    price: 15999,
    images: [
      'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800',
    ],
    category: 'industrial-remediation',
    stock: 50,
    rating: 4.9,
    reviewCount: 67,
    benefits: [
      'Neutralizes soil contaminants',
      'Certified for industrial use',
      'Promotes soil recovery',
      'Meets environmental standards',
      'Bulk discounts available',
    ],
    specifications: [
      { label: 'Weight', value: '1000 kg (bulk)' },
      { label: 'pH Level', value: 'Adjustable' },
      { label: 'Treatment', value: 'Chemical neutralization' },
      { label: 'Certification', value: 'EPA approved' },
    ],
    tags: ['industrial', 'remediation', 'professional'],
    certifications: ['EPA Approved', 'Industrial Grade'],
    featured: false,
    popular: false,
  },
  {
    id: '4',
    name: 'Organic Lawn Fertilizer Soil',
    slug: 'organic-lawn-fertilizer-soil',
    description: 'Transform your lawn with our nutrient-rich organic soil blend. Designed to promote lush, green grass growth while improving soil structure and water retention.',
    shortDescription: 'For vibrant, healthy lawns',
    price: 799,
    originalPrice: 999,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    ],
    category: 'garden-lawn',
    stock: 120,
    rating: 4.6,
    reviewCount: 312,
    benefits: [
      'Promotes thick, green grass',
      '100% organic ingredients',
      'Improves water retention',
      'Safe for pets and children',
      'Slow-release nutrients',
    ],
    specifications: [
      { label: 'Weight', value: '20 kg' },
      { label: 'Coverage', value: 'Up to 500 sq ft' },
      { label: 'NPK Ratio', value: '10-5-5' },
      { label: 'Type', value: '100% Organic' },
    ],
    tags: ['organic', 'lawn', 'fertilizer', 'pet-safe'],
    certifications: ['Organic Certified', 'Pet Safe'],
    featured: true,
    popular: true,
  },
  {
    id: '5',
    name: 'Cactus & Succulent Mix',
    slug: 'cactus-succulent-mix',
    description: 'Specially formulated for cacti and succulents, this fast-draining soil mix prevents water-logging and root rot while providing essential nutrients.',
    shortDescription: 'Perfect for cacti and succulents',
    price: 349,
    images: [
      'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=800',
    ],
    category: 'indoor-planting',
    subcategory: 'specialty',
    stock: 180,
    rating: 4.8,
    reviewCount: 156,
    benefits: [
      'Excellent drainage',
      'Prevents root rot',
      'Contains sand and perlite',
      'pH optimized for desert plants',
      'Lightweight formula',
    ],
    specifications: [
      { label: 'Weight', value: '5 kg' },
      { label: 'pH Level', value: '6.0 - 7.5' },
      { label: 'Drainage', value: 'Very Fast' },
      { label: 'Components', value: 'Sand, Perlite, Peat' },
    ],
    tags: ['succulent', 'cactus', 'indoor', 'drainage'],
    featured: false,
    popular: true,
  },
  {
    id: '6',
    name: 'Raised Bed Garden Soil',
    slug: 'raised-bed-garden-soil',
    description: 'Complete soil solution for raised bed gardens. This premium mix combines the perfect balance of drainage, aeration, and nutrient retention for productive vegetable gardening.',
    shortDescription: 'Optimized for raised bed gardening',
    price: 899,
    images: [
      'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=800',
    ],
    category: 'garden-lawn',
    stock: 95,
    rating: 4.9,
    reviewCount: 203,
    benefits: [
      'Perfect for raised beds',
      'High organic content',
      'Excellent water retention',
      'Rich in nutrients',
      'Weed-free formula',
    ],
    specifications: [
      { label: 'Weight', value: '40 kg' },
      { label: 'Coverage', value: '1 cubic foot' },
      { label: 'pH Level', value: '6.5 - 7.0' },
      { label: 'Organic Content', value: '50%' },
    ],
    tags: ['raised-bed', 'vegetables', 'organic', 'garden'],
    certifications: ['Organic Certified'],
    featured: true,
    popular: true,
  },
  {
    id: '7',
    name: 'Organic Compost Premium',
    slug: 'organic-compost-premium',
    description: 'Rich, mature compost that enhances soil fertility naturally. Perfect for amending garden beds, enriching potting mixes, and top-dressing lawns.',
    shortDescription: 'Nutrient-rich organic compost',
    price: 599,
    images: [
      'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800',
    ],
    category: 'garden-lawn',
    stock: 160,
    rating: 4.7,
    reviewCount: 178,
    benefits: [
      'Improves soil structure',
      'Increases nutrient content',
      '100% organic matter',
      'Enhances water retention',
      'Promotes beneficial microbes',
    ],
    specifications: [
      { label: 'Weight', value: '15 kg' },
      { label: 'Maturity', value: 'Fully composted' },
      { label: 'Organic Content', value: '100%' },
      { label: 'Moisture', value: '40-50%' },
    ],
    tags: ['compost', 'organic', 'fertilizer', 'soil-amendment'],
    certifications: ['Organic Certified'],
    featured: false,
    popular: true,
  },
  {
    id: '8',
    name: 'Seed Starting Mix',
    slug: 'seed-starting-mix',
    description: 'Sterile, fine-textured growing medium perfect for starting seeds. Provides ideal moisture retention and aeration for germination and early seedling growth.',
    shortDescription: 'Perfect for seed germination',
    price: 399,
    images: [
      'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800',
    ],
    category: 'garden-lawn',
    stock: 210,
    rating: 4.8,
    reviewCount: 145,
    benefits: [
      'Sterile formula prevents disease',
      'Fine texture for small seeds',
      'Excellent moisture control',
      'Promotes strong root growth',
      'Disease-free guarantee',
    ],
    specifications: [
      { label: 'Weight', value: '8 kg' },
      { label: 'pH Level', value: '5.8 - 6.2' },
      { label: 'Sterilized', value: 'Yes' },
      { label: 'Texture', value: 'Fine' },
    ],
    tags: ['seeds', 'germination', 'seedling', 'starting'],
    featured: false,
    popular: false,
  },
  {
    id: '9',
    name: 'Orchid Potting Mix',
    slug: 'orchid-potting-mix',
    description: 'Specialized blend for orchids featuring bark, charcoal, and perlite. Provides excellent drainage and air circulation required for healthy orchid roots.',
    shortDescription: 'Specially formulated for orchids',
    price: 499,
    images: [
      'https://images.unsplash.com/photo-1551893478-c4142e6b0b10?w=800',
    ],
    category: 'indoor-planting',
    subcategory: 'specialty',
    stock: 125,
    rating: 4.9,
    reviewCount: 98,
    benefits: [
      'Excellent air circulation',
      'Superior drainage',
      'Contains fir bark',
      'Charcoal for freshness',
      'Long-lasting formula',
    ],
    specifications: [
      { label: 'Weight', value: '4 kg' },
      { label: 'Main Component', value: 'Fir Bark' },
      { label: 'pH Level', value: '5.5 - 6.5' },
      { label: 'Drainage', value: 'Excellent' },
    ],
    tags: ['orchid', 'indoor', 'specialty', 'epiphyte'],
    featured: false,
    popular: false,
  },
  {
    id: '10',
    name: 'Vegetable Garden Soil',
    slug: 'vegetable-garden-soil',
    description: 'Nutrient-dense soil blend specifically formulated for growing vegetables. Rich in organic matter with balanced nutrients for maximum yield.',
    shortDescription: 'Optimized for vegetable growth',
    price: 749,
    originalPrice: 949,
    images: [
      'https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=800',
    ],
    category: 'garden-lawn',
    stock: 140,
    rating: 4.8,
    reviewCount: 267,
    benefits: [
      'High nutrient content',
      'Balanced NPK ratio',
      'Rich in organic matter',
      'Ideal pH for vegetables',
      'Promotes high yields',
    ],
    specifications: [
      { label: 'Weight', value: '30 kg' },
      { label: 'Coverage', value: 'Up to 250 sq ft' },
      { label: 'pH Level', value: '6.5 - 7.0' },
      { label: 'NPK Ratio', value: '5-5-5' },
    ],
    tags: ['vegetables', 'organic', 'garden', 'high-yield'],
    certifications: ['Organic Certified'],
    featured: true,
    popular: true,
  },
  {
    id: '11',
    name: 'Bonsai Tree Soil Mix',
    slug: 'bonsai-tree-soil-mix',
    description: 'Premium bonsai soil with perfect drainage and aeration. Contains akadama, pumice, and lava rock for traditional bonsai cultivation.',
    shortDescription: 'Professional bonsai growing medium',
    price: 699,
    images: [
      'https://images.unsplash.com/photo-1525923838299-2312b60f6d69?w=800',
    ],
    category: 'indoor-planting',
    subcategory: 'specialty',
    stock: 85,
    rating: 4.9,
    reviewCount: 76,
    benefits: [
      'Traditional bonsai components',
      'Excellent drainage',
      'Prevents compaction',
      'Supports fine roots',
      'Professional grade',
    ],
    specifications: [
      { label: 'Weight', value: '5 kg' },
      { label: 'Components', value: 'Akadama, Pumice, Lava Rock' },
      { label: 'pH Level', value: '6.0 - 7.0' },
      { label: 'Grain Size', value: '3-6mm' },
    ],
    tags: ['bonsai', 'specialty', 'indoor', 'professional'],
    featured: false,
    popular: false,
  },
  {
    id: '12',
    name: 'Rose Garden Soil',
    slug: 'rose-garden-soil',
    description: 'Specially formulated for roses with optimal pH and nutrients. Promotes vibrant blooms and healthy growth for all rose varieties.',
    shortDescription: 'Perfect for beautiful roses',
    price: 649,
    images: [
      'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    ],
    category: 'garden-lawn',
    stock: 110,
    rating: 4.7,
    reviewCount: 134,
    benefits: [
      'pH balanced for roses',
      'Promotes vibrant blooms',
      'Rich in organic matter',
      'Contains bone meal',
      'Disease-resistant formula',
    ],
    specifications: [
      { label: 'Weight', value: '20 kg' },
      { label: 'pH Level', value: '6.0 - 6.5' },
      { label: 'Coverage', value: 'Up to 150 sq ft' },
      { label: 'Special Additives', value: 'Bone Meal, Blood Meal' },
    ],
    tags: ['roses', 'flowers', 'garden', 'blooms'],
    featured: false,
    popular: true,
  },
  {
    id: '13',
    name: 'Container Garden Mix',
    slug: 'container-garden-mix',
    description: 'Lightweight potting soil perfect for container gardening on patios, balconies, and terraces. Excellent drainage and nutrient retention.',
    shortDescription: 'Ideal for pots and containers',
    price: 549,
    images: [
      'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800',
    ],
    category: 'indoor-planting',
    stock: 175,
    rating: 4.6,
    reviewCount: 156,
    benefits: [
      'Lightweight formula',
      'Perfect for containers',
      'Good water retention',
      'Slow-release fertilizer',
      'Versatile use',
    ],
    specifications: [
      { label: 'Weight', value: '12 kg' },
      { label: 'pH Level', value: '6.0 - 7.0' },
      { label: 'Drainage', value: 'Excellent' },
      { label: 'Fertilizer', value: '3 months' },
    ],
    tags: ['container', 'patio', 'balcony', 'versatile'],
    featured: false,
    popular: true,
  },
  {
    id: '14',
    name: 'Topsoil Premium Grade',
    slug: 'topsoil-premium-grade',
    description: 'High-quality topsoil for landscaping, lawn repair, and garden bed preparation. Screened and enriched with organic matter.',
    shortDescription: 'Premium topsoil for landscaping',
    price: 849,
    images: [
      'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?w=800',
    ],
    category: 'garden-lawn',
    stock: 200,
    rating: 4.5,
    reviewCount: 189,
    benefits: [
      'Screened and clean',
      'Rich in nutrients',
      'Great for lawn repair',
      'Versatile application',
      'Bulk available',
    ],
    specifications: [
      { label: 'Weight', value: '50 kg' },
      { label: 'Coverage', value: 'Up to 300 sq ft (1 inch depth)' },
      { label: 'pH Level', value: '6.5 - 7.5' },
      { label: 'Screening', value: '10mm' },
    ],
    tags: ['topsoil', 'landscaping', 'lawn', 'bulk'],
    featured: false,
    popular: false,
  },
  {
    id: '15',
    name: 'Herb Garden Mix',
    slug: 'herb-garden-mix',
    description: 'Specially blended for growing culinary and medicinal herbs. Excellent drainage with balanced nutrients for flavorful harvests.',
    shortDescription: 'Perfect for kitchen herbs',
    price: 429,
    images: [
      'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800',
    ],
    category: 'garden-lawn',
    stock: 145,
    rating: 4.8,
    reviewCount: 198,
    benefits: [
      'Ideal for culinary herbs',
      'Excellent drainage',
      'Organic ingredients',
      'Enhances flavor',
      'Suitable for pots or beds',
    ],
    specifications: [
      { label: 'Weight', value: '10 kg' },
      { label: 'pH Level', value: '6.0 - 7.0' },
      { label: 'Drainage', value: 'Good' },
      { label: 'Best For', value: 'Basil, Thyme, Rosemary, Mint' },
    ],
    tags: ['herbs', 'culinary', 'organic', 'kitchen-garden'],
    certifications: ['Organic Certified'],
    featured: false,
    popular: true,
  },
];

// Mock reviews
export const mockReviews: Review[] = [
  {
    id: '1',
    productId: '1',
    userName: 'Priya Sharma',
    rating: 5,
    title: 'Best soil I\'ve used!',
    comment: 'My vegetable garden has never looked better. The tomatoes are thriving, and the drainage is perfect. Highly recommend!',
    date: '2024-10-15',
    verified: true,
    helpful: 24,
  },
  {
    id: '2',
    productId: '1',
    userName: 'Rajesh Kumar',
    rating: 4,
    title: 'Great quality soil',
    comment: 'Very good product. My plants are growing well. Only minor issue was delivery took a bit longer than expected.',
    date: '2024-10-10',
    verified: true,
    helpful: 12,
  },
  {
    id: '3',
    productId: '2',
    userName: 'Anjali Mehta',
    rating: 5,
    title: 'Perfect for my houseplants',
    comment: 'My monstera and pothos are loving this mix. No more root rot issues!',
    date: '2024-09-28',
    verified: true,
    helpful: 18,
  },
];

// Mock testimonials
export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Vikram Patel',
    role: 'Home Gardener',
    content: 'Soil Guard has transformed my garden. Their expert advice and quality products have helped me grow the best vegetables I\'ve ever had!',
    rating: 5,
  },
  {
    id: '2',
    name: 'Sneha Reddy',
    role: 'Landscape Designer',
    company: 'GreenScape Designs',
    content: 'As a professional, I trust Soil Guard for all my projects. Their industrial solutions are top-notch and their support team is incredibly helpful.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Arun Desai',
    role: 'Urban Farmer',
    content: 'The chatbot helped me choose the perfect soil for my rooftop garden. Customer service is excellent, and the products deliver results!',
    rating: 5,
  },
];

// Mock FAQs
export const mockFAQs: FAQ[] = [
  {
    question: 'How do I choose the right soil for my needs?',
    answer: 'Use our AI assistant to help you find the perfect soil! Click the chat button and tell us about your project - whether it\'s indoor plants, a garden, or industrial use. Our assistant will recommend the best products based on your specific needs.',
  },
  {
    question: 'What makes Soil Guard products different?',
    answer: 'All our soil products are certified for quality and tested for optimal pH levels, nutrient content, and drainage properties. We use sustainable sourcing and ensure each batch meets strict standards for organic content and environmental safety.',
  },
  {
    question: 'Do you offer bulk discounts?',
    answer: 'Yes! We offer significant discounts for bulk orders, especially for industrial and commercial projects. Contact our sales team or use the chat feature to get a custom quote.',
  },
  {
    question: 'What is your return policy?',
    answer: 'We offer a 30-day satisfaction guarantee. If you\'re not completely satisfied with your purchase, you can return unopened bags for a full refund. Please refer to our Returns & Refunds page for complete details.',
  },
  {
    question: 'How long does delivery take?',
    answer: 'Standard delivery takes 3-5 business days within major cities. For remote areas, delivery may take up to 7 business days. Free shipping is available on orders over ₹2,000.',
  },
];
